# Generated by Django 2.2.7 on 2019-11-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rede', '0001_initial'),
        ('nave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Festival')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('convidados', models.ManyToManyField(related_name='convidado_para', to='rede.Pessoa')),
                ('encontro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='festival.Encontro')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nave.Espaco')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Festival')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede.Rede')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_por', to='rede.Pessoa')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Subcategoria')),
                ('tag', models.ManyToManyField(to='festival.Tag')),
            ],
        ),
    ]
