# Generated by Django 2.2.7 on 2019-11-10 16:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nave', '0003_auto_20191109_2233'),
        ('rede', '0002_pessoa_redes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Festivais',
            },
        ),
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Festival')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=64)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='festival.Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('categorias', mptt.fields.TreeManyToManyField(to='festival.Categoria')),
                ('convidados', models.ManyToManyField(related_name='convidado_para', to='rede.Pessoa')),
                ('encontro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='festival.Encontro')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nave.Espaco')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Festival')),
                ('rede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rede.Rede')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_por', to='rede.Pessoa')),
            ],
        ),
    ]
