# Generated by Django 2.2.7 on 2019-11-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festival',
            options={'verbose_name_plural': 'Festivais'},
        ),
    ]
