# Generated by Django 2.2.7 on 2019-11-10 15:44

from django.db import migrations

def cria_categorias(apps, schema_editor):
    Categoria = apps.get_model('festival', 'Categoria')

    kwargs = dict(lft=0, rght=0, tree_id=0, level=0)

    maonamassa = Categoria.objects.create(**kwargs, nome='Mão na Massa')
    Categoria.objects.create(parent=maonamassa, **kwargs, nome='Oficina')
    Categoria.objects.create(parent=maonamassa, **kwargs, nome='Maratona')
    Categoria.objects.create(parent=maonamassa, **kwargs, nome='Experimentação')
    Categoria.objects.create(parent=maonamassa, **kwargs, nome='Criação')

    conexao = Categoria.objects.create(**kwargs, nome='Conexão')
    Categoria.objects.create(parent=conexao, **kwargs, nome='Papo (é tipo 1 pessoa que manda o rap)')
    Categoria.objects.create(parent=conexao, **kwargs, nome='Roda de conversa (mais elaborado um cadinho)')
    Categoria.objects.create(parent=conexao, **kwargs, nome='Mesa power')
    Categoria.objects.create(parent=conexao, **kwargs, nome='Demonstrações')

    vibes = Categoria.objects.create(**kwargs, nome='Vibes')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Festa (Balbúrdia)')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Show')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Exposição')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Instalações')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Tour Cultural')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Performances')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Batalha Slam')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Playlists')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Imersão')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Feirinha')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Corpo')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Terapia')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Yoga')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Alimentação')
    Categoria.objects.create(parent=vibes, **kwargs, nome='Exibição')

    tag = Categoria.objects.create(**kwargs, nome='Tag')
    Categoria.objects.create(parent=tag, **kwargs, nome='Comunidade ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Comportamento ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Movimento Social')
    Categoria.objects.create(parent=tag, **kwargs, nome='Mídia Ativismo')
    Categoria.objects.create(parent=tag, **kwargs, nome='Comunicação')
    Categoria.objects.create(parent=tag, **kwargs, nome='Formação Livre ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Hospedagem Solidária ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Agenda ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Mobilização')
    Categoria.objects.create(parent=tag, **kwargs, nome='Feminismos ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Negritude ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Sustentabilidade')
    Categoria.objects.create(parent=tag, **kwargs, nome='Moeda Social ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Finanças Solidárias ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Internacional')
    Categoria.objects.create(parent=tag, **kwargs, nome='Política ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Eleições')
    Categoria.objects.create(parent=tag, **kwargs, nome='Música')
    Categoria.objects.create(parent=tag, **kwargs, nome='Amazônia ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Meio Ambiente')
    Categoria.objects.create(parent=tag, **kwargs, nome='Cinema ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Audiovisual ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Gastronomia ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Vegano ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Vegetariano')
    Categoria.objects.create(parent=tag, **kwargs, nome='Música ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Distribuição Audiovisual')
    Categoria.objects.create(parent=tag, **kwargs, nome='Periferia')
    Categoria.objects.create(parent=tag, **kwargs, nome='Estudantes')
    Categoria.objects.create(parent=tag, **kwargs, nome='Pod Cast')
    Categoria.objects.create(parent=tag, **kwargs, nome='festivais')
    Categoria.objects.create(parent=tag, **kwargs, nome='Login Unico')
    Categoria.objects.create(parent=tag, **kwargs, nome='Moda ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Produtos')
    Categoria.objects.create(parent=tag, **kwargs, nome='Financiamento')
    Categoria.objects.create(parent=tag, **kwargs, nome='Literatura ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Slam ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Poesia')
    Categoria.objects.create(parent=tag, **kwargs, nome='Agência')
    Categoria.objects.create(parent=tag, **kwargs, nome='Fotografia')
    Categoria.objects.create(parent=tag, **kwargs, nome='Produtos Orgânicos')
    Categoria.objects.create(parent=tag, **kwargs, nome='Tecnologia')
    Categoria.objects.create(parent=tag, **kwargs, nome='Segurança Digital ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Drone ')
    Categoria.objects.create(parent=tag, **kwargs, nome='Devs    ')
    Categoria.objects.create(parent=tag, **kwargs, nome='territorios ')
    Categoria.objects.create(parent=tag, **kwargs, nome='urbanismo ')
    Categoria.objects.create(parent=tag, **kwargs, nome='cidade ')
    Categoria.objects.create(parent=tag, **kwargs, nome='arquitetura ')
    Categoria.objects.create(parent=tag, **kwargs, nome='direito')
    Categoria.objects.create(parent=tag, **kwargs, nome='Body Positive')


def remove_categorias(apps, schema_editor):
    Categoria = apps.get_model('festival', 'Categoria')
    Categoria.objects.filter(nome='Mão na Massa').delete()
    Categoria.objects.filter(nome='Conexão').delete()
    Categoria.objects.filter(nome='Tag').delete()
    Categoria.objects.filter(nome='Vibes').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cria_categorias, remove_categorias),
    ]
