# Generated by Django 2.2.7 on 2019-11-12 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_auto_20191110_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('nome',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='atividade',
            name='encontro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festival.Encontro'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rede.Rede'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tags',
            field=models.ManyToManyField(to='festival.Tag'),
        ),
    ]
