# Generated by Django 2.2.7 on 2019-11-12 01:48

from django.db import migrations

def cria_tags(apps, schema_editor):
    Categoria = apps.get_model('festival', 'Categoria')
    Tag = apps.get_model('festival', 'Tag')

    cat_tag = Categoria.objects.get(nome='Tag')

    for categoria in Categoria.objects.filter(parent=cat_tag):
        tag = Tag.objects.create(nome=categoria.nome)
        for atividade in categoria.atividade_set.all():
            tag.atividade_set.add(atividade)
            categoria.atividade_set.remove(atividade)

    cat_tag.delete()

def remove_tags(apps, schema_editor):
    Tag = apps.get_model('festival', 'Tag')
    Tag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_auto_20191112_0148'),
    ]

    operations = [
        migrations.RunPython(cria_tags, remove_tags),
    ]
