# Generated by Django 2.2.7 on 2019-11-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0005_cria_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tags',
            field=models.ManyToManyField(blank=True, to='festival.Tag'),
        ),
    ]
