# Generated by Django 2.2.7 on 2019-11-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0006_auto_20191113_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='pendente',
            field=models.BooleanField(default=True),
        ),
    ]
