# Generated by Django 2.2.7 on 2019-11-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0010_auto_20191113_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='coincide_horario',
            field=models.BooleanField(default=False),
        ),
    ]
