# Generated by Django 2.2.7 on 2019-11-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0011_atividade_coincide_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='ordem',
            field=models.IntegerField(default=1),
        ),
    ]
