# Generated by Django 2.2.7 on 2019-11-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0012_atividade_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
    ]
