# Generated by Django 2.2.7 on 2019-11-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0013_auto_20191117_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='ordem',
            new_name='coluna',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='coincide_horario',
        ),
    ]
