# Generated by Django 2.2.7 on 2019-11-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0006_auto_20191113_0146'),
        ('festival', '0014_auto_20191117_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='convidados',
        ),
        migrations.AddField(
            model_name='atividade',
            name='convidades',
            field=models.ManyToManyField(blank=True, related_name='convidade_para', to='rede.Pessoa'),
        ),
    ]
