# Generated by Django 2.2.7 on 2019-11-18 13:03

from django.db import migrations
from django.db.models import Q
from datetime import datetime, timedelta

def acerta_colunas(apps, schema_editor):
    Atividade = apps.get_model('festival', 'Atividade')
    Espaco = apps.get_model('nave', 'Espaco')

    for espaco in Espaco.objects.all():
        relevant = Atividade.objects.filter(espaco=espaco,
                                            inicio__isnull=False,
                                            fim__isnull=False)
        atividades = list(relevant)
        colunas = 1
        for dia in (21, 22, 23, 24):
            for hora in range(24):
                inicio = datetime(2019, 11, dia, hora)
                fim = inicio + timedelta(0, 0, 0, 0, 0, 1)
                time_filters = (Q(inicio__lte=inicio,
                                  fim__gt=inicio) |
                                Q(inicio__lt=fim,
                                  fim__gte=fim) |
                                Q(inicio__lte=inicio,
                                  fim__gte=fim) |
                                Q(inicio__gte=inicio,
                                  fim__lte=fim))
                qs = relevant.filter(time_filters).order_by('coluna')
                colunas = max(colunas, qs.count())
                coluna = 1
                for at in qs.all():
                    at.coluna = coluna
                    at.save()
                    coluna += 1
        espaco.colunas = colunas
        espaco.save()

    Atividade.objects.filter(espaco__isnull=True).update(coluna=1)


def back(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0015_auto_20191117_2338'),
        ('nave', '0009_auto_20191118_1323'),
    ]

    operations = [
        migrations.RunPython(acerta_colunas, back),
    ]
