# Generated by Django 2.2.7 on 2019-11-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espaco',
            options={'verbose_name': 'Espaço'},
        ),
    ]
