# Generated by Django 2.2.7 on 2019-11-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0002_auto_20191109_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='andar',
            options={'verbose_name_plural': 'Andares'},
        ),
    ]
