# Generated by Django 2.2.7 on 2019-11-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0003_auto_20191109_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaco',
            name='capacidade',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
