# Generated by Django 2.2.7 on 2019-11-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0004_espaco_capacidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaco',
            name='eventos_simultaneos',
            field=models.IntegerField(default=1),
        ),
    ]
