# Generated by Django 2.2.7 on 2019-11-17 14:42

from django.db import migrations

def ordena(apps, schema_editor):
    Espaco = apps.get_model('nave', 'Espaco')
    ordem = 1
    for espaco in Espaco.objects.all():
        espaco.ordem = ordem
        espaco.save()
        ordem += 1

def back(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0006_espaco_ordem'),
    ]

    operations = [
        migrations.RunPython(ordena, back),
    ]
