# Generated by Django 2.2.7 on 2019-11-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0007_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espaco',
            options={'ordering': ['ordem'], 'verbose_name': 'Espaço'},
        ),
    ]
