# Generated by Django 2.2.7 on 2019-11-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0008_auto_20191117_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espaco',
            old_name='eventos_simultaneos',
            new_name='colunas',
        ),
    ]
