# Generated by Django 2.2.7 on 2019-11-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0002_pessoa_redes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rede',
            name='nome',
            field=models.CharField(max_length=64),
        ),
    ]
