# Generated by Django 2.2.7 on 2019-11-10 15:44

from django.db import migrations

def cria_redes(apps, schema_editor):
    Rede = apps.get_model('rede', 'Rede')

    Rede.objects.create(nome='Fora do Eixo')
    Rede.objects.create(nome='Midia Ninja')
    Rede.objects.create(nome='Universidade Ninja')
    Rede.objects.create(nome='Hospeda Cultura')
    Rede.objects.create(nome='Calendario Cultural')
    Rede.objects.create(nome='Ella')
    Rede.objects.create(nome='Banco Paul Singer')
    Rede.objects.create(nome='Cultura de Red')
    Rede.objects.create(nome='500 CIDADES')
    Rede.objects.create(nome='Candidate-se')
    Rede.objects.create(nome='Design Ativista')
    Rede.objects.create(nome='Som - Sistema Operacional da Musica')
    Rede.objects.create(nome='Campanha de mulher')
    Rede.objects.create(nome='342')
    Rede.objects.create(nome='Midia India')
    Rede.objects.create(nome='TV NINJA - PosTV')
    Rede.objects.create(nome='Xepa')
    Rede.objects.create(nome='Rede brasil de festivais')
    Rede.objects.create(nome='Emergencias')
    Rede.objects.create(nome='Proxima Cena')
    Rede.objects.create(nome='Perifa Talks')
    Rede.objects.create(nome='Estudantes Ninja')
    Rede.objects.create(nome='Ninja AMBIENTAL')
    Rede.objects.create(nome='NINJACAST')
    Rede.objects.create(nome='Faccion')
    Rede.objects.create(nome='Grito Rock')
    Rede.objects.create(nome='IDA')
    Rede.objects.create(nome='Loja Ninja')
    Rede.objects.create(nome='Financia Ninja')
    Rede.objects.create(nome='Ninja Livros')
    Rede.objects.create(nome='Gandaia agencia e distro de musica.')
    Rede.objects.create(nome='Seda')
    Rede.objects.create(nome='Poeticas Visuais')
    Rede.objects.create(nome='Vira Voto')
    Rede.objects.create(nome='Comentariado')
    Rede.objects.create(nome='Parlamento Ninja')
    Rede.objects.create(nome='Armazem do Campo')
    Rede.objects.create(nome='Armario Coletivo')
    Rede.objects.create(nome='Drone Lab.')
    Rede.objects.create(nome='Casa Amazonia')
    Rede.objects.create(nome='Casas Coletivas')
    Rede.objects.create(nome='Hacker Space')


def remove_redes(apps, schema_editor):
    Rede = apps.get_model('rede', 'Rede')
    Rede.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0003_auto_20191110_1628'),
    ]

    operations = [
        migrations.RunPython(cria_redes, remove_redes),
    ]
