# Generated by Django 2.2.7 on 2019-11-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0004_cria_redes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='rede',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rede',
            name='nome',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
